### ISSUE TITLE
Change name of the --dump option to --file

### ISSUE THREAD

**Issue by ubbeK** [Starcounter/StarDump#13]
@k-rus mentioned that we should change the name of `--dump` option during the demo for unity. It should be called `--file`.

Update README.md aswell.

**Comment by miyconst** [comment]
Also need to update readme and [Migrating from 2.2 to 2.4](https://starcounter.io/guides/tools/migrating-2-2-2-4/) pages after this change.

**Comment by ubbeK** [comment]
Code + README + starcounter.io changed

closing
