### ISSUE TITLE
Make sure that database is empty before reloading

### ISSUE THREAD

**Issue by miyconst** [Starcounter/StarDump#18]
Comes from - [sccrud.star_crud_CreateObjectWithId does not check for ID duplication](https://github.com/Starcounter/Starcounter.Core/issues/143).

StarDump reload should check for any existing objects in the database, if any found it should fail with a proper message.

@ubbeK take this one if you have some time, otherwise I will implement it.

**Comment by ubbeK** [comment]
@miyconst: Sure. I think this behavior may be activated by default but the user must be able to deactivate it through CLI, example: `StarDump.exe reload --database mydb --file somefile.sqlite --forcereload`
Someone might want to combine two databases.

**Comment by miyconst** [comment]
>... but the user must be able to deactivate it through CLI ...

Then we should clearly indicate in the manuals that user should take care about object ID uniqueness on their own.

**Comment by ubbeK** [comment]
This issue has been implemented through `Starcounter.Metadata.RawView -> Updatable` property. If all are false, then the database is at its initial state.

Closing
