### ISSUE TITLE
Specify default values for skip-prefixes

### ISSUE THREAD

**Issue by ubbeK** [Starcounter/StarDump#22]
The default values for SkipColumnPrefixes and SkipTablePrefixes are defined in [Configuration.cs](https://github.com/Starcounter/StarDump/blob/master/src/StarDump.Common/Model/Configuration.cs#L16-L17). 

These needs to be specified in the console, i.e. `StarDump unload --help`.

**Comment by ubbeK** [comment]
@miyconst Or do you think it is better to always add the default values even these options are set:

Example:

`StarDump unload -db default -f c:/file.sqlite3 --skiptableprefixes="MyDbClass1., MyDbClass2."`

would result in 

`{ "Starcounter.", "Concepts.", "SocietyObjects.", "MyDbClass1.", "MyDbClass2" }`

which mean we could skip the specification in console

**Comment by miyconst** [comment]
Hm, this is a question. The `"Starcounter.", "Concepts."` are most likely will be always skipped, but `"SocietyObjects."` is a class library, and if someone uses it same way as Simplified, it should be unloaded.

We can add another CLI parameter like `--also-skiptableprefixes` or `--add-skiptableprefixes` which would not replace the value, but rather add values.

**Comment by ubbeK** [comment]
> Hm, this is a question. The "Starcounter.", "Concepts." are most likely will be always skipped,

In what scenario might they be used? If they won't ever be used, they should be set in a different constant array and never displayed/shown to the user. If so, we may still keep `--skiptableprefixes` as overwrite-able as today but only have `SocietyObjects.` which is displayed in `--help` as default.

**Comment by miyconst** [comment]
Sound like the way to go. Please implement it.

**Comment by ubbeK** [comment]
I consider this issue to be invalid because of this commit: https://github.com/Starcounter/StarDump/commit/5864c8888e682261eafbece874af2b6ea6fddd28 => #39 

Closing
