### ISSUE TITLE
Add --verbose option

### ISSUE THREAD

**Issue by ubbeK** [Starcounter/StarDump#24]
Add `--verbose` option to StarDump and [Configuration.cs](https://github.com/Starcounter/StarDump/blob/master/src/StarDump.Common/Model/Configuration.cs#L14).

It should also be included in `Output.cs`

|  Verbose | WriteErrorLine  | WriteWarningLine  | WriteLine  |
|---|---|---|---|
| <= 0  |   |   |   |
| = 1  | X  |   |   |
| = 2  | X  | X  |   |
| else  | X  | X  | X  |

Default value be set to write everything

**Comment by per-samuelsson** [comment]
> Default value be set to write everything

I think otherwise that standard is the opposite, showing just the minimal as the default.

**Comment by per-samuelsson** [comment]
As for logging, in the past, we've mostly used something like this to define severity levels:

http://stackoverflow.com/a/2031209/888042

Even though not everyone follow it in all our code. 😄. Also, we've used the level of *notice* instead of *info*.

**Comment by ubbeK** [comment]
> I think otherwise that standard is the opposite, showing just the minimal as the default.

I see. Maybe the "Write"-sections should be cut somewhat different than what is described in the table above since it feels kind of strange not to show the stack trace by default if an error occurs. 

I feel like default should show Errors, Warnings and Info. Then there might be a Debug state that show a whole lot more and a Quite state. Will have to take a deeper look and take some inspiration from the logging.

**Comment by per-samuelsson** [comment]
> I feel like default should show Errors, Warnings and Info.

Then go with that, seems reasonable to me.

**Comment by warpech** [comment]
> I think otherwise that standard is the opposite, showing just the minimal as the default.

This is actually one of the key rules in Unix programs:

> #### Rule of Silence: When a program has nothing surprising to say, it should say nothing.
>
> One of Unix's oldest and most persistent design rules is that when a program has nothing interesting or surprising to say, it should shut up. Well-behaved Unix programs do their jobs unobtrusively, with a minimum of fuss and bother. Silence is golden.

[source](http://www.catb.org/~esr/writings/taoup/html/ch01s06.html#id2878339)

**Comment by ubbeK** [comment]
This issue has been implemented with the following

|  Verbose | Error | Warning  | Notice | Info | Debug |
|---|---|---|---|---|---|
| <= 0  | X |   |   |   |   |
| = 1  | X  |  X |   |   |   |
| = 2  | X  | X  | X  |   |   |
| = 3  | X  | X  | X  |  X  |   |
| > 3  | X  | X  | X  |  X  |  X |

Where `Notice` is the default value which only writes (apart from `Error` and `Warning` lines) unload/reload start/finish information as following:

```
C:\GitHub\Starcounter\StarDump\src\StarDump [master ≡]> dotnet run unload --database=default --file=C:\Temp\test020.sqlite3
Unload started C:\Temp\test020.sqlite3
Unload finished C:\Temp\test020.sqlite3
Elapsed 00:00:01.3869221
Tables count 267
Rows count 46
```

Please reopen if we should change the default value.
