### ISSUE TITLE
Make sure core functionality is in a library, not in the tool

### ISSUE THREAD

**Issue by per-samuelsson** [Starcounter/StarDump#3]
https://github.com/per-samuelsson/Misc/wiki/Dumptool-(specification)#non-functional-requirements

**Comment by ubbeK** [comment]
Current structure of StarDump repo:

```
\src
    \StarDump (CLI)
    \StarDump.Common (Common files with StarDump.Migrator.2.2)
    \StarDump.Core (uses Starcounter.Core API)
\test
    \StarDump.Core.Tests
```

There are currently only dummy tests in `StarDump.Core.Tests`. May add another test project for explicitly testing the CLI.

**Comment by miyconst** [comment]
I think this issue is already fulfilled, so it can be closed. @per-samuelsson?

**Comment by ubbeK** [comment]
I believe it is, closing issue
