### ISSUE TITLE
Implement support for byte[] data type

### ISSUE THREAD

**Issue by miyconst** [Starcounter/StarDump#30]

**Comment by miyconst** [comment]
The support should be proven by an automated test. 

cc @linkdata

**Comment by miyconst** [comment]
Mr. @ubbeK do you think you will have a chance for this issue after migrating `StarDump` to the latest `Starcounter.Core`

**Comment by chrhol** [comment]
Just wanted to point out, that we (for legacy reason) also need to support the `Binary` struct, not only `byte[]`. I think at the moment that .Core only supports `byte[]`

**Comment by miyconst** [comment]
`Starcounter.Core` uses `byte[]` for exactly the same data which is `Binary` in `Level1`, so nothing special has to be made.

**Comment by ubbeK** [comment]
It completely depends on what has the highest priority, to start with our build system or StarDump.

**Comment by miyconst** [comment]
Take our build system, I take care about StarDump.

**Comment by miyconst** [comment]
Implemented, should be available in the tomorrow's nightly `2.3` build.
