### ISSUE TITLE
Decimal values are incorrectly serialized in SQL queries with custom localizations

### ISSUE THREAD

**Issue by miyconst** [Starcounter/StarDump#32]
When Swedish (and many other) locale applied, decimal separator is a comma, which generates incorrect SQL statements.

This should be fixed by setting neutral locale for entire app.

**Comment by miyconst** [comment]
@ubbeK please check that my fix (see the commit tagged above) solves the issue, run a teamcity build with custom branch and StarDump test, and merge to master.

**Comment by ubbeK** [comment]
First thing tomorrow!

**Comment by ubbeK** [comment]
TC builds successed for Develop and RC

**Comment by miyconst** [comment]
Closing this issue. Tests will be covered in another issues.
