### ISSUE TITLE
Convert from project.json to msbuild

### ISSUE THREAD

**Issue by ubbeK** [Starcounter/StarDump#34]
Duplicate from [Starcounter.Core](https://github.com/Starcounter/Starcounter.Core/issues/146).

This is not the highest priority since @linkdata supplied us with a `Nuget`-package for `Starcounter.Core,` but will have to do it when we need any new potential fixes from `Starcounter.Core`.

**Comment by ubbeK** [comment]
cc @miyconst

**Comment by miyconst** [comment]
Does `msbuild` work under Linux as well?

**Comment by linkdata** [comment]
> Does msbuild work under Linux as well?

Not sure. Probably. We don't invoke `msbuild` directly, so it doesn't really matter for us.

`dotnet build` will do what's needed.

**Comment by linkdata** [comment]
Check https://www.myget.org/feed/starcounter/package/nuget/Starcounter.Core to see which versions are available once you start on this. Currently it's 0.2.0-*. I'll try to remember to bump the version number when I break API compatibility.

**Comment by per-samuelsson** [comment]
>> Does msbuild work under Linux as well?
>
> Not sure. Probably. We don't invoke `msbuild` directly, so it doesn't really matter for us.
> `dotnet build` will do what's needed.

I would be surprised if it didn't, considering how close it's now integrated with .Core tooling, and knowing that tooling is promoted as cross-platform.

The way to run it  and assure you get the proper version for your tooling stack, is going via the new host, e.g:

`
dotnet msbuild /t:Rebuild /p:Configuration=Debug
`

**Comment by miyconst** [comment]
The project is now migrated to MsBuild and compatible with VS2017. Closing the issue.
