### ISSUE TITLE
Selective unload/reload

### ISSUE THREAD

**Issue by warpech** [Starcounter/StarDump#35]
Would be possible to do a selective `unload`, for example giving a table name or a SQL query as a parameter?

Is it possible at all to make a `reload` of that data to another database?

I am asking because we need a way to export and import blending data ([`Starcounter.HTMLComposition`](https://github.com/Starcounter/Starcounter/blob/develop/src/Starcounter.Extensions/HTMLComposition.cs), [`Simplified.Ring6.Web*`](https://github.com/StarcounterPrefabs/Simplified/tree/master/Ring6/Web)). I am looking for the most frictionless solution to this.

**Comment by ubbeK** [comment]
With the current implementation you can exclude Tables and Columns with specific prefixes, see `-scp` and `-stp` options below.

```
C:\Github\Starcounter\StarDump\src\StarDump [issue_29 ≡]> dotnet run unload -?
Project StarDump.Common (.NETCoreApp,Version=v1.0) was previously compiled. Skipping compilation.
Project StarDump.Core (.NETCoreApp,Version=v1.0) was previously compiled. Skipping compilation.
Project StarDump (.NETCoreApp,Version=v1.0) was previously compiled. Skipping compilation.


Usage:  unload [options]

Options:
  -db | --database <DatabaseName>               Name of starcounter database to dump
  -f | --file <FileName>                        Output dump filename
  -b | --buffersize <BufferSize>                Set insert rows buffer size to dump database.
  -scp | --skipcolumnprefixes <ColumnPrefixes>  Column prefixes to skip, space and/or comma separated. Example: -scp="a b,c"
  -stp | --skiptableprefixes <TablePrefixes>    Table prefixes to skip, space and/or comma separated. Example: -stp="a b ,c"
  -? | -h | --help                              Show help information
```

This means that you would have to remove everything that you don't want. Accept from that there is no current way to do this.

**Comment by warpech** [comment]
How about `reload` - if I load SQL to a non-empty database, will it crash on duplicate Object IDs, or assign new ones?

**Comment by miyconst** [comment]
It will crash. The reload is supposed to be executed over a newly created database.

**Comment by warpech** [comment]
Is there some possibility to specify an ID offset to `reload`, or automatically use the first available value from the database? Assuming that there is data integrity within the SQL dump, this could work just fine.

**Comment by miyconst** [comment]
It is possible to implement, but not currently available.

**Comment by warpech** [comment]
Given the problem presented in the last paragraph of the first comment, do you think that would be a good solution? Or do you have any alternatives? 

Using a REST API for sending data between two Starcounter installations sounds ridiculous to me.

**Comment by miyconst** [comment]
>... do you think that would be a good solution?

I think it would be a good solution, but it has different purpose of what StarDump is currently doing. We may extent it's functionality to support import/export alongside with unload/reload. Export will accept list of tables to export, and not list of tables to skip. Import will accept an object id offset or will determine the next object id itself.

**Comment by warpech** [comment]
@dan31 could we set up some priority on this then? This is imporant for blending track, otherwise it is impossible to share blending config between Starcounter instances.

**Comment by miyconst** [comment]
@warpech now there is a new parameter `--unloadtables` which can be used to unload only some of the tables. See the latest [readme](https://github.com/Starcounter/StarDump).

Tomorrow's nightly build should include this change.

Please close the issue if you are satisfied.

**Comment by warpech** [comment]
Will I be able to reload these tables to a non-empty database?

**Comment by miyconst** [comment]
Yes, but you have to use `--forcereload` parameter to reload to a not empty database.

**Comment by warpech** [comment]
Sounds great. We will check if that works in https://github.com/StarcounterApps/Launcher/issues/222. 

Closing this issue as done.

**Comment by miyconst** [comment]
@warpech there is a possible issue. The object number in the database dump and existing database should not collide. Otherwise you will end up with a corrupted database.

Is this is problem for you?

**Comment by warpech** [comment]
Then it certainly is a problem. It would be really good to have a `--reassignids` flag that treats the ids within the SQL input as foreign key relations, but actually reassigns them to non-taken ids.

**Comment by miyconst** [comment]
Okay.. this has to be added. I will work on it.

**Comment by miyconst** [comment]
[Implement --reassignids flag](https://github.com/Starcounter/StarDump/issues/49).
