### ISSUE TITLE
Adopt StarDump to a (first) breaking change in 2.3

### ISSUE THREAD

**Issue by dan31** [Starcounter/StarDump#36]
@k-rus @bigwad and others: please initiate such changes to StarDump on your own any time breaking change is introduced.
@miyconst unfortunately you did not join today's meeting, where you should have gotten to know about this change to be included. Please join next time.
Currently: @k-rus introduced a breaking change at _today's_ build. @k-rus please provide details to @miyconst.
Hence, somehow ```stardump``` needs to start understanding those changes and act correspondingly.
Currently I cannot propose our customers to move to updated version of RC because there is no support in StarDump (as I suppose). Thus, the issue is urgent.

**Comment by k-rus** [comment]
> Currently: @k-rus introduced a breaking change at today's build. @k-rus please provide details to @miyconst.
> Hence, somehow stardump needs to start understanding those changes and act correspondingly.

This breaking change does not allow to start old database, but should not affect stardump itself. I don't see any need to take an action. If you see that stardump fails, then let us know.

**Comment by miyconst** [comment]
>Currently: @k-rus introduced a breaking change at today's build. @k-rus please provide details to @miyconst.

Is it API breaking change or what? If it's a breaking change for StarDump, then it's also a breaking change Starcounter.Core.

>Hence, somehow stardump needs to start understanding those changes and act correspondingly.

StarDump can fail with an exception of missing API methods, but I don't think it is required to teach it to investigate what are the new API methods.

**Comment by miyconst** [comment]
>This breaking change does not allow to start old database, but should not affect stardump itself. I don't see any need to take an action. If you see that stardump fails, then let us know.

Actually, this is not true. The database starts, but not the apps inside the database. Will Starcounter.Core work without starting the database?

**Comment by k-rus** [comment]
> This breaking change does not allow to start old database, but should not affect stardump itself. I don't see any need to take an action. If you see that stardump fails, then let us know.
> Actually, this is not true. The database starts, but not the apps inside the database. Will Starcounter.Core work without starting the database?

To my experience first start of the database fails, the second succeeds, but then starting application fails.

If the database is from previous Starcounter installation, then behaviour is undefined. Actually, metalayer reports another version number, but as I see this is not utilised yet.

You should not use stardump from new Starcounter installation for accessing old database.

**Comment by miyconst** [comment]
>You should not use stardump from new Starcounter installation for accessing old database.

So, the migration way is not changed?

1. Unload database with StarDump.
2. Install new version of Starcounter.
3. Reload database with StarDump.

The step 3 should work now and does not require changes in StarDump. Am I right @k-rus?

**Comment by k-rus** [comment]
> So, the migration way is not changed?
> 
> Unload database with StarDump.
> Install new version of Starcounter.
> Reload database with StarDump.
> The step 3 should work now and does not require changes in StarDump. Am I right @k-rus?

I think so. I haven't tested, but I see no reason not to work. I actually don't understand why this issue was created.

**Comment by miyconst** [comment]
I tried to check whether everything works as it should, but there is no today's builds, only a custom one from @chrhol which does not include StarDump, and @k-rus told me not to use old StarDump with new Starcounter.

Will be first thing to check tomorrow, if the builds pass.

**Comment by miyconst** [comment]
Still no fresh builds :(

**Comment by bigwad** [comment]
Something happened to artefacts upload. cc @alemoi 
But you still can download setup directly from the teamcity: https://teamcity.starcounter.org/repository/download/Starcounter_V23NightlyWindows/20103:id/Starcounter-RC-2.3.0.5781-Setup.exe

**Comment by andwah** [comment]
I checked the logs on the download server,   
The new uploads fails to build, due to some signing failure.  I will investigate more....

**Comment by k-rus** [comment]
> @k-rus told me not to use old StarDump with new Starcounter.

You can use old StarDump. The only breaking change is that starting old database image on new Starcounter will not work.

**Comment by andwah** [comment]
About the build failure: https://github.com/Starcounter/AdminTrack/issues/249

**Comment by alemoi** [comment]
Yeah, its the cert schema I changed yesterday, forgot that we sign on download server as well.  Will fix promptly.

**Comment by miyconst** [comment]
>... But you still can download setup directly from the teamcity:  ...

Thanks @bigwad. I got it from there.

**Comment by miyconst** [comment]
@dan31, @k-rus I just went through the migration steps between incompatible 2.3 versions and everything works as expected.

Migrated from `Starcounter-RC-2.3.0.5767` to `Starcounter-RC-2.3.0.5781`.

@dan31, what should be done in scope of this issue? What should be adopted?

>Hence, somehow stardump needs to start understanding those changes and act correspondingly.

What exactly the StarDump tool should start understand?

**Comment by andwah** [comment]
Build/Download server issue now resolved. Starcounter/AdminTrack#249

**Comment by dan31** [comment]
@miyconst I think this is all for StarDump. Further discussion is moved to https://github.com/Starcounter/Starcounter/issues/4119.
