### ISSUE TITLE
StarDump is not installing on 2.4.0.1492 .. 2.4.0.1536

### ISSUE THREAD

**Issue by SenerDemiral** [Starcounter/StarDump#40]

**Comment by miyconst** [comment]
@alemoi please take a look.

**Comment by alemoi** [comment]
I don't think I know much about StarDump myself but let's see.

@SenerDemiral can you please provide a more extended description of the problem with StarDump?

**Comment by miyconst** [comment]
@alemoi the problem is that it is not included in the installer. @SenerDemiral correct me if I am wrong.

**Comment by SenerDemiral** [comment]
Yes it is not included in the installer.

**Comment by alemoi** [comment]
That clarifies things! Sure, I will check tomorrow what's the reason.

**Comment by alemoi** [comment]
It was just disabled for develop. Now I enabled it and next nightly should contain StarDump. Thanks for reporting!
