### ISSUE TITLE
stardump reload/unload unrecognized option

### ISSUE THREAD

**Issue by robinjoh** [Starcounter/StarDump#48]
I'm running starcounter 2.3.0.6270. When trying to use stardump reload/unload the command prompt tells me the given command is an unrecognized option. 

I use the following syntax, as described at your website:
stardump reload --database test --file FILEPATH

The full exception is as follows:
Microsoft.Extensions.CommandLineUtils.CommandParsingException: Unrecognized option 'reload'
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.HandleUnexpectedArg(CommandLineApplication command, String[] args, Int32 index, String argTypeName)
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at StarDump.CommandLineInterface.Execute(String[] args) in C:\TeamCity\BuildAgent\work\sc-4667\StarDump\src\StarDump\CommandLineInterface.cs:line 32

Is this a bug or have you changed the syntax in Starcounter 2.3.0.6270?

**Comment by miyconst** [comment]
This command seems to be correct:

```
stardump reload --database test --file FILEPATH
```

I will check the exact same Starcounter version.

**Comment by miyconst** [comment]
I am not able to reproduce the issue. Please provide more info.

- What is your Windows version.
- What is the installation path, and from where you execute the command.
- What is the full text of the command you try to execute.

**Comment by robinjoh** [comment]
Hello again!

My windows version is 64 bit Windows 10.

The installation path is C:\Program Files\Starcounter. I execute the command from C:\Program Files\Starcounter\Stardump.

The full text i try to execute is:
stardump reload --database Default --file C:\Users\Robin\Desktop\devgr.sqlite3

I can add that i run the command in the windows command prompt with administrator rights.

**Comment by miyconst** [comment]
Hi @robinjoh.

Sorry for the late reply. Unfortunately I was not able to reproduce the issue :(.
Could you please try to:

- Install the latest Starcounter 2.3.
- Reboot machine.
- Try to unload/reload again.

If that still does not work, I would appreciate if you can demonstrate it via screen sharing.

**Comment by miyconst** [comment]
Archiving the issue. Please feel free to reopen if you have any more details.
