### ISSUE TITLE
Implement --reassignids flag

### ISSUE THREAD

**Issue by miyconst** [Starcounter/StarDump#49]
If the flag is set, StarDump should calculate the max used id inside a database and use it as an offset for all the new entire imported from a dump.

**Comment by miyconst** [comment]
Implemented.

**Comment by miyconst** [comment]
Now there are two extra properties - `-offset` and `-reassign`, @warpech please see the readme for more details.

**Comment by warpech** [comment]
This looks brilliant! 

Just a note about the parameter naming. I think that having a shorthand `-offset` for `--insertobjectnooffset` and `-reassign` for `--reassignobjectno ` is not doing much benefit. It just increases the API surface. Shorthands should be really short or they don't make much sense.

Compare with Git: https://git-scm.com/docs/git-commit
