### ISSUE TITLE
Stardump performance optimization

### ISSUE THREAD

**Issue by bigwad** [Starcounter/StarDump#55]
Stardump runs inside a single database transaction, hence it's important to do the job as fast as possible to reduce memory pressure.
Is it single-threaded?

**Comment by ubbeK** [comment]
One `System.Threading.Tasks.Task` is created per `Table`, one fore creating the Table and another for reloading the rows into that Table.

**Comment by bigwad** [comment]
We have means of running parallel `Db.Transact()` sharing the same snapshot, so that it's possible to make unload multithreaded
https://github.com/Starcounter/level1/issues/4020
https://github.com/Starcounter/Starcounter.Core/issues/141

**Comment by ubbeK** [comment]
We currently have parallel tasks when unload, but they are all run in the same `Db.Transact()`. But are you saying that it is better to have one `Db.Transact()` per task which shares the same snapshot?

**Comment by bigwad** [comment]
>We currently have parallel tasks when unload, but they are all run in the same  Db.Transact() .

How is that possible?

**Comment by ubbeK** [comment]
https://github.com/Starcounter/StarDump/blob/eb0cf3b8ef6420ad3d567ca664dfbcdd5113889f/src/StarDump.Core/Unload.cs#L56-L83

**Comment by bigwad** [comment]
Ok, I see. Db.Transact is not shared because it can't. Instead, tasks in parallel processes prepared data, that are being prepared in a single thread. When I ran StarDump it looked like it loads only a single core, so I guess preparation is more expensive operation than actual processing. And you may use aforementioned transaction cloning to parallelize preparation.

**Comment by ubbeK** [comment]
> And you may use aforementioned transaction cloning to parallelize preparation.

Awesome! 

> We have means of running parallel Db.Transact() sharing the same snapshot, so that it's possible to make unload multithreaded
> Starcounter/level1#4020
> Starcounter/Starcounter.Core#141

But I cannot find any API or commit reference in the referenced issues. What branches is it pused to, is Starcounter.Core nuget package updated with it, any example on how to use it?

cc @linkdata

**Comment by linkdata** [comment]
https://github.com/Starcounter/Starcounter.Core/blob/develop/src/Starcounter.Core.Snapshot/SnapshotTransactionFactory.cs

Example usage in the tests.

https://github.com/Starcounter/Starcounter.Core/blob/develop/test/Starcounter.Core.Snapshot.Tests/Tests.cs

**Comment by ubbeK** [comment]
> https://github.com/Starcounter/Starcounter.Core/blob/develop/src/Starcounter.Core.Snapshot/SnapshotTransactionFactory.cs
> 
> Example usage in the tests.
> 
> https://github.com/Starcounter/Starcounter.Core/blob/develop/test/Starcounter.Core.Snapshot.Tests/Tests.cs

Thanks

**Comment by miyconst** [comment]
This issue is even more important due to [Implement support for byte[] data type](https://github.com/Starcounter/StarDump/issues/30) implementation.

Now the `binary` and `string` data are unloaded as named parameters, and not inline SQL, which is slower, but is the only way to unload `binary` and huge `string` values.

**Comment by miyconst** [comment]
@bigwad I tried to unload rows in parallel threads using same snapshot as you suggested, but it fails hard.

I am using `sccoredb.star_context_get_setspec` method to get set specifier per object. It returns a pointer to a Bluestar string, but this does not seem to be thread safe, and while I am still reading the value, some other threads are replacing this value.

Just to clarify: currently StarDump iterates through all database records in a single thread once. Unloading value into SQLite is performed in many threads.

If I run a thread per table it becomes inefficient, since `SELECT x FROM X x` will also return the rows of ancestors and I have to filter those out, this is where `star_context_get_setspec` fails.

Another option is to calculate count of the rows, and split them in chunks with `TAKE` & `OFFSET`, but as far as I know `COUNT`/`TAKE`/`OFFSET` is not yet supported by NewQP, and even if it's supported, `OFFSET` still requires iterating over the rows multiple times. When it's all solved `star_context_get_setspec` will still fail due to multi thread access.

**Comment by bigwad** [comment]
You have to use individual context for each thread. Do you?

**Comment by miyconst** [comment]
>You have to use individual context for each thread. Do you?

Yeah. That fixed the multi thread issue with `star_context_get_setspec`, but this solution ends up being significantly slower than single iteration over `MotherOfAllLayouts` table.

**Comment by bigwad** [comment]
I guess you have an intermediate step between retrieving a database object and unloading it to SQLite -
 that would be serialization of a database object to some POCO-like object to be unloaded. Right? I haven't profiled stardump, but I guess it takes more time than retrieving object id's.
Then with transaction cloning, you can parallelize serialization or probably even skip it entirely.

**Comment by miyconst** [comment]
Yes, StarDump has in-memory proxy objects with copy of database values, those objects are used to flush data into SQLite.

The thing is that iterating over database in multi thread scenario and filter the rows by set specifier itself is slower then iterating over `MotherOfAllLayouts` once with flushing the data into SQLite.

**Comment by bigwad** [comment]
>The thing is that iterating over database in multi thread scenario and filter the rows by set specifier itself is slower then iterating over MotherOfAllLayouts once with flushing the data into SQLite.

As I said. Iterate in one thread and parallelize serialization and dumping. And probably you won't even need serialization.

**Comment by miyconst** [comment]
>As I said. Iterate in one thread and parallelize serialization and dumping. And probably you won't even need serialization.

This means that Starcounter transaction has to be open until SQLite finishes it's work. My goal was to reduce the Starcounter transaction time as much as possible.

Here are the numbers I currently have.

| Action                                                                                         | Time              |
|---------------------------------------------------------------------|----------------|
| Unload **with** intermediate `Dictionary<string, object>`        | `3.5` seconds |
| Unload **without** intermediate `Dictionary<string, object>`  | `3.4` seconds |

Database info: `452` tables, `229486` rows.

I don't think that the pain worth the gain. Also it complicates debugging a lot.

**Comment by bigwad** [comment]
> probably you won't even need serialization

**probably**. It's a bonus if you think it's worth. If not, just parallelize the serialization.

**Comment by bigwad** [comment]
But again, I haven't profiled and suggest it assuming serialization takes most of the time during preparation.

**Comment by bigwad** [comment]
>This means that Starcounter transaction has to be open until SQLite finishes it's work. My goal was to reduce the Starcounter transaction time as much as possible.

It depends. Imagine a database that barely fits RAM - with cloning you effectively double required memory. So it may not only be slower due to paging, it also will slow down other database apps.

**Comment by miyconst** [comment]
>it assuming serialization takes most of the time during preparation.

Serialization is requires in any way, but there are two options:

- Open transaction.
- Read row values and save into `Dictionary<string, value>`.
- Close transaction.
- Generate SQL query + parameters out of the dictionary.
- Execute SQL.

And second option.

- Open transaction.
- Generate SQL query + parameters with database values.
- Execute SQL query.
- Close transaction.

So, in the first case there is a `Dictionary<string, object>` middleman, in the second case the values are directly serialized to string/object values of SQL query/parameters.

**Comment by miyconst** [comment]
>... with cloning you effectively double required memory. 

No, because it happens in chunks. As soon as a chunk of rows is flushed to SQLite the memory is freed. The worst case of double ram is required only when SQLite is not able to finish a single write and entire database is already read.

**Comment by bigwad** [comment]
>As soon as a chunk of rows is flushed to SQLite the memory is freed.

Then it's producer/consumer and unbound queue. If the producer (serialization) is faster than the queue will grow and in worst case double required memory. If the consumer (SQ lite dumping) is faster or you limit the queue to block producer then producer's lifetime is bound to consumer throughput, i.e. transaction would be open until consumer finishes.

Here is the trade-off you have to make, but it's irrelevant to the point of the issue. The point is to parallelize serialization (be it a separate step or integrated with actual dumping).

**Comment by miyconst** [comment]
Okay. As investigation shows the pain does not worth the gain, at least now I don't want to spend time for it. Will see whether it will be important in the future.

Archiving the issue for now.
