### ISSUE TITLE
Bump Starcounter.Core and .NET Core version in StarDump

### ISSUE THREAD

**Issue by ubbeK** [Starcounter/StarDump#58]
Lets bump the Starcounter.Core version to the latest in StarDump and .NET Core 2.0 target framework.

@linkdata Any API changes that concerns StarDump? What is the latest Starcounter.Core version?

**Comment by linkdata** [comment]
https://github.com/Starcounter/Starcounter.Core/releases/tag/v0.6.0-alpha

**Comment by miyconst** [comment]
Work in progress - https://github.com/Starcounter/StarDump/tree/sc.core-0.6.0.

**Comment by miyconst** [comment]
Already done a few times.
