### ISSUE TITLE
Create a StarDump.Console self contained package

### ISSUE THREAD

**Issue by miyconst** [Starcounter/StarDump#6]
The `StarDump.Console` application should be self contained and ready for distribution on Tuesday (`2016.12.20`).

Here is a nice tutorial how to publish a .NET Core app - [Self-contained .NET Core Applications](http://www.hanselman.com/blog/SelfcontainedNETCoreApplications.aspx). You can also take a look at this commit - [Update project.json for a self contained app](https://github.com/Starcounter/StarDump/commit/eee592744c430cd0219c256a0e1ebb9cf1f48967).

We plan to demonstrate the very first version of StarDump on Wednesday's release planning meeting.

Please let me know if you need any help or assistance.

cc @dan31

**Comment by ubbeK** [comment]
fixed, closing issue
