### ISSUE TITLE
Upgrade to Starcounter.Core 0.6.0

### ISSUE THREAD

**Issue by miyconst** [Starcounter/StarDump#61]
@linkdata I tried to install `Starcounter.Core 0.6.0` like this:

```xml
<PackageReference Include="Starcounter.Core" Version="0.6.0-*" />
```

But the downloaded package contains only `Starcounter.Core` reference, which does not seem right. Trying same thing with `0.5.0` products complete list of assemblies.

What am I missing?

**Comment by Mackiovello** [comment]
To get the complete list of assemblies you have to include `Starcounter.Core.AspNetCore`.

**Comment by miyconst** [comment]
Thanks @Mackiovello, it worked.
