### ISSUE TITLE
Unable to connect to a database if it's started in Level1

### ISSUE THREAD

**Issue by miyconst** [Starcounter/StarDump#74]
**Steps to reproduce**

- `staradmin kill all`
- `staradmin start server`
- `staradmin new db test`
- `staradmin start db test`
- `StarDump unload --database test --file C:\test.sqlite3`

```
Starcounter.Core.StarcounterException: ScErrDataManagerChannelInUse (SCERR4294): Failed to connect to data manager because designated channel is in use. Occurs if a previous client is still connected or not yet properly disconnected.
   at Starcounter.Core.Hosting.Connection.ConnectToDataManager(StarcounterOptions options)
   at Starcounter.Core.Hosting.Connection.Start()
   at Starcounter.Core.Hosting.DefaultAppHost.Start()
   at StarDump.Core.Unload.Run() in C:\TeamCity\BuildAgent\work\sc-11661\StarDump\src\StarDump.Core\Unload.cs:line 50
   at StarDump.Core.CommandInterface.Unload(Configuration config, Output output) in C:\TeamCity\BuildAgent\work\sc-11661\StarDump\src\StarDump.Core\CommandInterface.cs:line 78
   at StarDump.CommandLineInterface.<>c__DisplayClass9_1.<AddUnloadCommand>b__1() in C:\TeamCity\BuildAgent\work\sc-11661\StarDump\src\StarDump\CommandLineInterface.cs:line 182
```

**Comment by miyconst** [comment]
```
<PackageReference Include="Starcounter.Core" Version="0.5.0-*" />
```

**Comment by miyconst** [comment]
```
Starcounter-RC-2.3.1.7954 (Dec 2, 2017 1:02:08 AM)
```

**Comment by miyconst** [comment]
cc @linkdata

**Comment by linkdata** [comment]
That's some error being returned by the kernel. Ask @bigwad .

**Comment by miyconst** [comment]
![image](https://user-images.githubusercontent.com/6435556/33547414-4cf8479a-d8e4-11e7-90d1-2f48853ca9ed.png)

**Comment by linkdata** [comment]
Possibly related to https://github.com/Starcounter/level1/issues/4376
cc @chrhol

**Comment by miyconst** [comment]
>Possibly related to Starcounter/level1#4376

Not related, since the issue also persists in the versions prior to the fix from @chrhol.

**Comment by linkdata** [comment]
I was referring to [this comment](https://github.com/Starcounter/level1/issues/4376#issuecomment-348443501), where @chrhol observes the same error from another test:

```
[10:01:49][DropTable_test-bat] [10:02:05, Critical, Starcounter (droptabledb)]
[10:01:49][DropTable_test-bat] Starcounter.DbException: ScErrDataManagerChannelInUse (SCERR4294): Failed to connect to data manager because designated channel is in use. Occurs if a previous client is still connected or not yet properly disconnected.
```

Having that same very rare error occuring in two different areas so close in time is unlikely to be a coincidence. Or is the `DropTable_test-bat` test also using Nova?

**Comment by chrhol** [comment]
I was not able to reproduce that error again, and there are several successful builds after my change (not to mention that the change have been in develop for quite some time), so it will be interesting to see what the cause is. 

Do you get this every time @miyconst, or once in a while? I did do an unload using stardump a couple of weeks ago in `2.3.1`, so it's should be something recent.

**Comment by bigwad** [comment]
The problem is the context number limitation. There is a hard limit of 31 contexts per running database instance. With current architecture, client processes should somehow agree on sharing those contexts to let everyone live. 
Code host by default takes min(Number_of_CPUs, 31). And Nova by default takes min(Number_of_CPUs*2, 24).

**Comment by linkdata** [comment]
So NumCPU*3 > 31? They're running on a hexacore machine with HT?

**Comment by bigwad** [comment]
octa

**Comment by linkdata** [comment]
Workarounds:

* In StarDump, call `.UseSchedulerCount(schedulerCount)` to specify a scheduler count.

* Change the database config files to specify a scheduler count. Nova should use that value just as level1 should.

**Comment by miyconst** [comment]
>Do you get this every time @miyconst, or once in a while? I did do an unload using stardump a couple of weeks ago in `2.3.1`, so it's should be something recent.

I get it every time.

>Code host by default takes min(Number_of_CPUs, 31). And Nova by default takes min(Number_of_CPUs*2, 24).

Heads had the same issue on a two core Virtual Machine.

**Comment by bigwad** [comment]
>Heads had the same issue on a two core Virtual Machine.

It might be something unrelated or more probably they unnoticed client processes hanging. Do we have an issue on that?

**Comment by linkdata** [comment]
If there is a way to get the number of currently free schedulers from Bluestar, that would be useful.

If if that's not possible, coding around it should be possible. Catch `StarcounterException` when connecting to Bluestar. If it's `SCERR4294`, decrement the requested scheduler count and retry.

**Comment by miyconst** [comment]
>It might be something unrelated or more probably they unnoticed client processes hanging. Do we have an issue on that?

No, since I didn't have much time for debugging, and reproduced the same issue locally, so I thought it't same cause. Let's first fix the issue on my machine, and then I try to debug on their server.

**Comment by miyconst** [comment]
Fixed by adding `--scheduler-count` parameter with default value of `2`, the Heads issue will be investigated further outside of this issue.
